from __future__ import annotations

from collections import Counter
from collections.abc import Mapping
from datetime import UTC, datetime
from typing import Any

from app.services.trigger_engine import TriggerSeverity
from app.storage.snapshot_store import SnapshotStore
from app.services.snapshot_replay_models_core import SnapshotReplayResult
from app.services.snapshot_replay_models_source_timing import (
    SnapshotMappedAtAlignmentConsistency,
    SnapshotMappedAtAlignmentConsistencyEntry,
    SnapshotSourceDiagnosticsFreshnessEvaluationModeDrift,
    SnapshotSourceDiagnosticsFreshnessEvaluationModeDriftEntry,
    SnapshotSourceFreshnessDecayTimeline,
    SnapshotSourceFreshnessDecayTimelineEntry,
    SnapshotSourceFreshnessPolicyDrift,
    SnapshotSourceFreshnessPolicyDriftEntry,
    SnapshotSourceFreshnessStatusThresholdReconciliation,
    SnapshotSourceFreshnessStatusThresholdReconciliationEntry,
    SnapshotSourceFreshnessSummaryReconciliation,
    SnapshotSourceFreshnessSummaryReconciliationEntry,
    SnapshotSourceObservationAvailabilityLagDrift,
    SnapshotSourceObservationAvailabilityLagDriftEntry,
    SnapshotSourceObservationCadenceDrift,
    SnapshotSourceObservationCadenceEntry,
    SnapshotSourceObservationFreshnessSecondsDrift,
    SnapshotSourceObservationFreshnessSecondsDriftEntry,
    SnapshotSourceObservationNormalizationModeDrift,
    SnapshotSourceObservationNormalizationModeDriftEntry,
    SnapshotSourceObservationTimestampIntegrityDrift,
    SnapshotSourceObservationTimestampIntegrityDriftEntry,
    SnapshotStaleSourceListThresholdReconciliation,
    SnapshotStaleSourceListThresholdReconciliationEntry,
)
from app.services.snapshot_replay_models_source_drift import (
    SnapshotSourceDiagnosticsAverageCoverageDrift,
    SnapshotSourceDiagnosticsAverageCoverageDriftEntry,
    SnapshotSourceDiagnosticsCriticalFeatureDrift,
    SnapshotSourceDiagnosticsCriticalFeatureDriftEntry,
    SnapshotSourceDiagnosticsHighSeverityDrift,
    SnapshotSourceDiagnosticsHighSeverityDriftEntry,
    SnapshotSourceDiagnosticsInfoFeatureDrift,
    SnapshotSourceDiagnosticsInfoFeatureDriftEntry,
    SnapshotSourceDiagnosticsReadyFeatureDrift,
    SnapshotSourceDiagnosticsReadyFeatureDriftEntry,
    SnapshotSourceDiagnosticsSeverityLabelDrift,
    SnapshotSourceDiagnosticsSeverityLabelDriftEntry,
    SnapshotSourceDiagnosticsSeverityRankDensityDrift,
    SnapshotSourceDiagnosticsSeverityRankDensityDriftEntry,
    SnapshotSourceDiagnosticsSeverityRankDrift,
    SnapshotSourceDiagnosticsSeverityRankDriftEntry,
    SnapshotSourceDiagnosticsSeverityRankSpreadDrift,
    SnapshotSourceDiagnosticsSeverityRankSpreadDriftEntry,
    SnapshotSourceDiagnosticsStaleFeatureDrift,
    SnapshotSourceDiagnosticsStaleFeatureDriftEntry,
    SnapshotSourceDiagnosticsWarningFeatureDrift,
    SnapshotSourceDiagnosticsWarningFeatureDriftEntry,
    SnapshotSourceDiagnosticsZeroRankDrift,
    SnapshotSourceDiagnosticsZeroRankDriftEntry,
    SnapshotSourceObservationConfidenceDrift,
    SnapshotSourceObservationConfidenceDriftEntry,
    SnapshotSourceObservationSummaryDrift,
    SnapshotSourceObservationSummaryDriftEntry,
)
from app.services.snapshot_replay_models_source_quality import (
    SnapshotRawPayloadReferenceCompleteness,
    SnapshotRawPayloadReferenceCompletenessEntry,
    SnapshotSourceDecisionUsageConsistency,
    SnapshotSourceDecisionUsageConsistencyEntry,
    SnapshotSourceDiagnosticsMinimumCoverageFloorReconciliation,
    SnapshotSourceDiagnosticsMinimumCoverageFloorReconciliationEntry,
    SnapshotSourceDiagnosticsMissingAssetCountReconciliation,
    SnapshotSourceDiagnosticsMissingAssetCountReconciliationEntry,
    SnapshotSourceDiagnosticsMissingSourceFeatureCountReconciliation,
    SnapshotSourceDiagnosticsMissingSourceFeatureCountReconciliationEntry,
    SnapshotSourceDiagnosticsSeverityRankingCriticalCountReconciliation,
    SnapshotSourceDiagnosticsSeverityRankingCriticalCountReconciliationEntry,
    SnapshotSourceDiagnosticsSeverityRankingFeatureCountReconciliation,
    SnapshotSourceDiagnosticsSeverityRankingFeatureCountReconciliationEntry,
    SnapshotSourceDiagnosticsSeverityRankingInfoCountReconciliation,
    SnapshotSourceDiagnosticsSeverityRankingInfoCountReconciliationEntry,
    SnapshotSourceDiagnosticsSeverityRankingNonActionableCountReconciliation,
    SnapshotSourceDiagnosticsSeverityRankingNonActionableCountReconciliationEntry,
    SnapshotSourceDiagnosticsSeverityRankingRankGapContinuityReconciliation,
    SnapshotSourceDiagnosticsSeverityRankingRankGapContinuityReconciliationEntry,
    SnapshotSourceDiagnosticsSeverityRankingRankGapMagnitudeReconciliation,
    SnapshotSourceDiagnosticsSeverityRankingRankGapMagnitudeReconciliationEntry,
    SnapshotSourceDiagnosticsSeverityRankingRankLabelConsistencyReconciliation,
    SnapshotSourceDiagnosticsSeverityRankingRankLabelConsistencyReconciliationEntry,
    SnapshotSourceDiagnosticsSeverityRankingRankOrderContinuityReconciliation,
    SnapshotSourceDiagnosticsSeverityRankingRankOrderContinuityReconciliationEntry,
    SnapshotSourceDiagnosticsSeverityRankingWarningCountReconciliation,
    SnapshotSourceDiagnosticsSeverityRankingWarningCountReconciliationEntry,
    SnapshotSourceDiagnosticsStaleAssetCountReconciliation,
    SnapshotSourceDiagnosticsStaleAssetCountReconciliationEntry,
    SnapshotSourceObservationRecordSummaryReconciliation,
    SnapshotSourceObservationRecordSummaryReconciliationEntry,
    SnapshotSourceRecordCompleteness,
    SnapshotSourceRecordCompletenessEntry,
    SnapshotVerifiedSourceCoverageReconciliation,
    SnapshotVerifiedSourceCoverageReconciliationEntry,
)
from app.services.snapshot_replay_models_source_registry import (
    SnapshotFallbackUsageRecurrence,
    SnapshotFallbackUsageRecurrenceEntry,
    SnapshotFallbackUsageTimelineEntry,
    SnapshotNoExecutionGuardrailConsistency,
    SnapshotNoExecutionGuardrailEntry,
    SnapshotPaperSafeSourceFlagConsistency,
    SnapshotPaperSafeSourceFlagConsistencyEntry,
    SnapshotProviderAdapterContractConsistency,
    SnapshotProviderAdapterContractConsistencyEntry,
    SnapshotSourceGapRecurrenceEntry,
    SnapshotSourceGapRecurrenceLeaderboard,
    SnapshotSourceRegistryBindingDrift,
    SnapshotSourceRegistryBindingDriftEntry,
    SnapshotSourceVerificationDrift,
    SnapshotSourceVerificationDriftEntry,
    SnapshotReplaySourceDiagnosticContractFieldSetDriftEntry,
    SnapshotReplaySourceDiagnosticContractFieldSetDrift,
    SnapshotReplayFullSurfaceResponseFieldSetConsistencyEntry,
    SnapshotReplayFullSurfaceResponseFieldSetConsistency,
)

SEVERITY_PRIORITY = {
    TriggerSeverity.INFO: 0,
    TriggerSeverity.YELLOW: 1,
    TriggerSeverity.ORANGE: 2,
    TriggerSeverity.RED: 3,
}

SOURCE_GAP_STATUS_PRIORITY = {
    'stale': 0,
    'missing': 1,
    'mixed': 2,
}

SOURCE_FRESHNESS_STATUS_PRIORITY = {
    'fresh': 0,
    'degraded': 1,
    'stale': 2,
}

ALLOWED_DECISION_USAGES = {
    "simulation_only",
    "verified_required",
}

EXPECTED_PROVIDER_ADAPTER_CONTRACT = "verified_provider_adapter_v1"
VALID_NORMALIZATION_MODES = {
    "batch_stored_at",
    "per_source_stored_at",
}
VALID_FRESHNESS_EVALUATION_MODES = {
    "observed",
    "not_evaluated",
}
HIGH_SEVERITY_MIN_RANK = 6
CRITICAL_SEVERITY_MIN_RANK = 8
WARNING_SEVERITY_MIN_RANK = 1
WARNING_SEVERITY_MAX_RANK = CRITICAL_SEVERITY_MIN_RANK - 1
INFO_SEVERITY_MAX_RANK = WARNING_SEVERITY_MIN_RANK - 1
ZERO_SEVERITY_RANK = 0
SEVERITY_LABEL_SCORES = {
    "critical": 3,
    "warning": 2,
    "info": 1,
}

__all__ = [
    "Any",
    "Counter",
    "Mapping",
    "UTC",
    "datetime",
    "TriggerSeverity",
    "SnapshotStore",
    "SnapshotReplayResult",
    "SEVERITY_PRIORITY",
    "SOURCE_GAP_STATUS_PRIORITY",
    "SOURCE_FRESHNESS_STATUS_PRIORITY",
    "ALLOWED_DECISION_USAGES",
    "EXPECTED_PROVIDER_ADAPTER_CONTRACT",
    "VALID_NORMALIZATION_MODES",
    "VALID_FRESHNESS_EVALUATION_MODES",
    "HIGH_SEVERITY_MIN_RANK",
    "CRITICAL_SEVERITY_MIN_RANK",
    "WARNING_SEVERITY_MIN_RANK",
    "WARNING_SEVERITY_MAX_RANK",
    "INFO_SEVERITY_MAX_RANK",
    "ZERO_SEVERITY_RANK",
    "SEVERITY_LABEL_SCORES",
    "SnapshotMappedAtAlignmentConsistency",
    "SnapshotMappedAtAlignmentConsistencyEntry",
    "SnapshotSourceDiagnosticsFreshnessEvaluationModeDrift",
    "SnapshotSourceDiagnosticsFreshnessEvaluationModeDriftEntry",
    "SnapshotSourceFreshnessDecayTimeline",
    "SnapshotSourceFreshnessDecayTimelineEntry",
    "SnapshotSourceFreshnessPolicyDrift",
    "SnapshotSourceFreshnessPolicyDriftEntry",
    "SnapshotSourceFreshnessStatusThresholdReconciliation",
    "SnapshotSourceFreshnessStatusThresholdReconciliationEntry",
    "SnapshotSourceFreshnessSummaryReconciliation",
    "SnapshotSourceFreshnessSummaryReconciliationEntry",
    "SnapshotSourceObservationAvailabilityLagDrift",
    "SnapshotSourceObservationAvailabilityLagDriftEntry",
    "SnapshotSourceObservationCadenceDrift",
    "SnapshotSourceObservationCadenceEntry",
    "SnapshotSourceObservationFreshnessSecondsDrift",
    "SnapshotSourceObservationFreshnessSecondsDriftEntry",
    "SnapshotSourceObservationNormalizationModeDrift",
    "SnapshotSourceObservationNormalizationModeDriftEntry",
    "SnapshotSourceObservationTimestampIntegrityDrift",
    "SnapshotSourceObservationTimestampIntegrityDriftEntry",
    "SnapshotStaleSourceListThresholdReconciliation",
    "SnapshotStaleSourceListThresholdReconciliationEntry",
    "SnapshotSourceDiagnosticsAverageCoverageDrift",
    "SnapshotSourceDiagnosticsAverageCoverageDriftEntry",
    "SnapshotSourceDiagnosticsCriticalFeatureDrift",
    "SnapshotSourceDiagnosticsCriticalFeatureDriftEntry",
    "SnapshotSourceDiagnosticsHighSeverityDrift",
    "SnapshotSourceDiagnosticsHighSeverityDriftEntry",
    "SnapshotSourceDiagnosticsInfoFeatureDrift",
    "SnapshotSourceDiagnosticsInfoFeatureDriftEntry",
    "SnapshotSourceDiagnosticsReadyFeatureDrift",
    "SnapshotSourceDiagnosticsReadyFeatureDriftEntry",
    "SnapshotSourceDiagnosticsSeverityLabelDrift",
    "SnapshotSourceDiagnosticsSeverityLabelDriftEntry",
    "SnapshotSourceDiagnosticsSeverityRankDensityDrift",
    "SnapshotSourceDiagnosticsSeverityRankDensityDriftEntry",
    "SnapshotSourceDiagnosticsSeverityRankDrift",
    "SnapshotSourceDiagnosticsSeverityRankDriftEntry",
    "SnapshotSourceDiagnosticsSeverityRankSpreadDrift",
    "SnapshotSourceDiagnosticsSeverityRankSpreadDriftEntry",
    "SnapshotSourceDiagnosticsStaleFeatureDrift",
    "SnapshotSourceDiagnosticsStaleFeatureDriftEntry",
    "SnapshotSourceDiagnosticsWarningFeatureDrift",
    "SnapshotSourceDiagnosticsWarningFeatureDriftEntry",
    "SnapshotSourceDiagnosticsZeroRankDrift",
    "SnapshotSourceDiagnosticsZeroRankDriftEntry",
    "SnapshotSourceObservationConfidenceDrift",
    "SnapshotSourceObservationConfidenceDriftEntry",
    "SnapshotSourceObservationSummaryDrift",
    "SnapshotSourceObservationSummaryDriftEntry",
    "SnapshotRawPayloadReferenceCompleteness",
    "SnapshotRawPayloadReferenceCompletenessEntry",
    "SnapshotSourceDecisionUsageConsistency",
    "SnapshotSourceDecisionUsageConsistencyEntry",
    "SnapshotSourceDiagnosticsMinimumCoverageFloorReconciliation",
    "SnapshotSourceDiagnosticsMinimumCoverageFloorReconciliationEntry",
    "SnapshotSourceDiagnosticsMissingAssetCountReconciliation",
    "SnapshotSourceDiagnosticsMissingAssetCountReconciliationEntry",
    "SnapshotSourceDiagnosticsMissingSourceFeatureCountReconciliation",
    "SnapshotSourceDiagnosticsMissingSourceFeatureCountReconciliationEntry",
    "SnapshotSourceDiagnosticsSeverityRankingCriticalCountReconciliation",
    "SnapshotSourceDiagnosticsSeverityRankingCriticalCountReconciliationEntry",
    "SnapshotSourceDiagnosticsSeverityRankingFeatureCountReconciliation",
    "SnapshotSourceDiagnosticsSeverityRankingFeatureCountReconciliationEntry",
    "SnapshotSourceDiagnosticsSeverityRankingInfoCountReconciliation",
    "SnapshotSourceDiagnosticsSeverityRankingInfoCountReconciliationEntry",
    "SnapshotSourceDiagnosticsSeverityRankingNonActionableCountReconciliation",
    "SnapshotSourceDiagnosticsSeverityRankingNonActionableCountReconciliationEntry",
    "SnapshotSourceDiagnosticsSeverityRankingRankGapContinuityReconciliation",
    "SnapshotSourceDiagnosticsSeverityRankingRankGapContinuityReconciliationEntry",
    "SnapshotSourceDiagnosticsSeverityRankingRankGapMagnitudeReconciliation",
    "SnapshotSourceDiagnosticsSeverityRankingRankGapMagnitudeReconciliationEntry",
    "SnapshotSourceDiagnosticsSeverityRankingRankLabelConsistencyReconciliation",
    "SnapshotSourceDiagnosticsSeverityRankingRankLabelConsistencyReconciliationEntry",
    "SnapshotSourceDiagnosticsSeverityRankingRankOrderContinuityReconciliation",
    "SnapshotSourceDiagnosticsSeverityRankingRankOrderContinuityReconciliationEntry",
    "SnapshotSourceDiagnosticsSeverityRankingWarningCountReconciliation",
    "SnapshotSourceDiagnosticsSeverityRankingWarningCountReconciliationEntry",
    "SnapshotSourceDiagnosticsStaleAssetCountReconciliation",
    "SnapshotSourceDiagnosticsStaleAssetCountReconciliationEntry",
    "SnapshotSourceObservationRecordSummaryReconciliation",
    "SnapshotSourceObservationRecordSummaryReconciliationEntry",
    "SnapshotSourceRecordCompleteness",
    "SnapshotSourceRecordCompletenessEntry",
    "SnapshotVerifiedSourceCoverageReconciliation",
    "SnapshotVerifiedSourceCoverageReconciliationEntry",
    "SnapshotFallbackUsageRecurrence",
    "SnapshotFallbackUsageRecurrenceEntry",
    "SnapshotFallbackUsageTimelineEntry",
    "SnapshotNoExecutionGuardrailConsistency",
    "SnapshotNoExecutionGuardrailEntry",
    "SnapshotPaperSafeSourceFlagConsistency",
    "SnapshotPaperSafeSourceFlagConsistencyEntry",
    "SnapshotProviderAdapterContractConsistency",
    "SnapshotProviderAdapterContractConsistencyEntry",
    "SnapshotSourceGapRecurrenceEntry",
    "SnapshotSourceGapRecurrenceLeaderboard",
    "SnapshotSourceRegistryBindingDrift",
    "SnapshotSourceRegistryBindingDriftEntry",
    "SnapshotSourceVerificationDrift",
    "SnapshotSourceVerificationDriftEntry",
    "SnapshotReplaySourceDiagnosticContractFieldSetDriftEntry",
    "SnapshotReplaySourceDiagnosticContractFieldSetDrift",
    "SnapshotReplayFullSurfaceResponseFieldSetConsistencyEntry",
    "SnapshotReplayFullSurfaceResponseFieldSetConsistency",
]
